apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-cpu-alert
  namespace: monitoring
spec:
  groups:
  - name: nginx.rules
    rules:
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"nginx-.*"}[5m]) > 0.5
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected on Nginx pod"
        description: "Nginx pod is consuming high CPU for more than 2 minutes."