grafana:
  service:
    type: LoadBalancer

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    type: LoadBalancer

alertmanager:
  alertmanagerSpec:
    replicas: 1
  service:
    type: LoadBalancer
